import {
  CAREER_START_DATE, CLUB_BY_CODE, CLUB_CATALOG, FIXTURES, RATING_OVERRIDES,
  RATING_SOURCE, ROSTER_SOURCE, SEASON_END_DATE, SEASON_ID, SEASON_LABEL,
  TEAM_BUDGETS, TEAM_ELO, rosterRowsFor
} from './season-2026-27.js';

export const SAVE_ID='primary';
const DAY=86400000;
const SHAPES={
  '4-2-3-1':{GK:1,DEF:4,MID:5,FWD:1},'4-3-3':{GK:1,DEF:4,MID:3,FWD:3},
  '3-4-2-1':{GK:1,DEF:3,MID:6,FWD:1},'4-4-2':{GK:1,DEF:4,MID:4,FWD:2}
};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
export function hashString(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function seededRandom(seed){let s=hashString(seed)||0x9e3779b9;return()=>{s+=0x6D2B79F5;let v=s;v=Math.imul(v^(v>>>15),v|1);v^=v+Math.imul(v^(v>>>7),v|61);return((v^(v>>>14))>>>0)/4294967296}}
export function addDays(date,n=1){const[y,m,d]=date.split('-').map(Number);return new Date(Date.UTC(y,m-1,d)+n*DAY).toISOString().slice(0,10)}
export function formatDate(date,short=false){const[y,m,d]=date.split('-').map(Number);return new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:short?'short':'long',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)))}
export function formatMoney(v){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'GBP',notation:'compact',maximumFractionDigits:1}).format(v||0)}
function finePosition(group,seed){const p={GK:['GK'],DEF:['CB','CB','RB','LB'],MID:['CM','CDM','CAM','RW','LW'],FWD:['ST','ST','CF','LW']}[group];return p[seed%p.length]}
function makePlayer(code,[name,group],i){const seed=hashString(`${code}:${name}`),base=Math.round(68+(TEAM_ELO[code]-1500)/43);const rating=RATING_OVERRIDES[name]||clamp(base+(seed%9)-4+(group==='FWD'?1:0),67,92);const age=18+(seed%17),potential=clamp(rating+(age<21?7:age<24?4:age<27?2:0),rating,93);const factor=age<23?1.35:age<27?1.12:age<31?.88:.58;return Object.freeze({id:`${code.toLowerCase()}-${i+1}-${seed.toString(36).slice(0,4)}`,clubCode:code,name,group,position:finePosition(group,seed),age,rating,potential,value:Math.max(750000,Math.round(Math.pow(rating-58,2.12)*90000*factor/250000)*250000),wage:Math.max(8000,Math.round((rating*rating*18+seed%22000)/1000)*1000),number:group==='GK'&&i===0?1:2+seed%97,ratingSource:RATING_SOURCE,rosterSource:ROSTER_SOURCE})}
export const SQUADS=Object.freeze(Object.fromEntries(CLUB_CATALOG.map(c=>[c.code,Object.freeze(rosterRowsFor(c.code).map((r,i)=>makePlayer(c.code,r,i)))])));
export const PLAYER_BY_ID=new Map(Object.values(SQUADS).flat().map(p=>[p.id,p]));
export const squadFor=code=>SQUADS[code]||[];
function initialPlayerState(code){return Object.fromEntries(squadFor(code).map(p=>[p.id,{condition:92+hashString(`${p.id}:c`)%9,sharpness:72+hashString(`${p.id}:s`)%25,morale:74+hashString(`${p.id}:m`)%23}]))}
export function autoPickLineup(code,formation='4-2-3-1',states={}){const shape=SHAPES[formation]||SHAPES['4-2-3-1'];const pool=[...squadFor(code)].sort((a,b)=>b.rating*(states[b.id]?.condition||100)-a.rating*(states[a.id]?.condition||100));const out=[];for(const g of ['GK','DEF','MID','FWD'])out.push(...pool.filter(p=>p.group===g).slice(0,shape[g]));out.push(...pool.filter(p=>!out.includes(p)).slice(0,11-out.length));return out.slice(0,11).map(p=>p.id)}
export function createCareer(code='MUN',now=new Date().toISOString()){const club=CLUB_BY_CODE.get(code)||CLUB_CATALOG[0],playerState=initialPlayerState(club.code),formation='4-2-3-1';return{schemaVersion:2,saveId:SAVE_ID,seasonId:SEASON_ID,seasonLabel:SEASON_LABEL,clubCode:club.code,managerName:'Gabriel Machado',createdAt:now,updatedAt:now,currentDate:CAREER_START_DATE,status:'active',formation,lineup:autoPickLineup(club.code,formation,playerState),tactics:{mentality:'Equilibrada',pressing:62,tempo:64,width:56,defensiveLine:58},trainingFocus:'Equilibrado',transferBudget:TEAM_BUDGETS[club.code],wageBudget:Math.round(TEAM_BUDGETS[club.code]*.009),boardConfidence:70,objectives:[club.elo>=1950?'Disputar o título da Premier League':club.elo>=1850?'Classificar para competições europeias':club.elo>=1750?'Terminar na metade superior':'Evitar o rebaixamento','Desenvolver dois jogadores sub-23','Manter as finanças sob controle'],results:{},playerState,playerStats:{},recentForm:[],inbox:[{id:'welcome',date:CAREER_START_DATE,sender:'Diretoria',subject:`Bem-vindo ao ${club.name}`,body:'Você tem onze dias para preparar o elenco antes da estreia da Premier League.',read:false},{id:'pack',date:CAREER_START_DATE,sender:'Analista',subject:'Pacote 2026/27 carregado',body:'Os 380 jogos, vinte clubes e elencos provisórios estão disponíveis offline.',read:false}],news:[],seasonSummary:null}}
export function normalizeCareer(c,code='MUN'){if(!c||c.schemaVersion!==2||!CLUB_BY_CODE.has(c.clubCode))return createCareer(code);const base=createCareer(c.clubCode,c.createdAt),states={...base.playerState,...(c.playerState||{})};return{...base,...c,tactics:{...base.tactics,...(c.tactics||{})},playerState:states,results:c.results||{},playerStats:c.playerStats||{},inbox:Array.isArray(c.inbox)?c.inbox:base.inbox,recentForm:Array.isArray(c.recentForm)?c.recentForm:[],lineup:Array.isArray(c.lineup)&&c.lineup.filter(id=>PLAYER_BY_ID.has(id)).length===11?c.lineup:autoPickLineup(c.clubCode,c.formation,states)}}
export const userFixtures=c=>FIXTURES.filter(f=>f.home===c.clubCode||f.away===c.clubCode);
export const fixturesOnDate=d=>FIXTURES.filter(f=>f.date===d);
export const nextUserFixture=c=>userFixtures(c).find(f=>!c.results[f.id])||null;
function teamProfile(c,code,home){const user=code===c.clubCode,ids=user?c.lineup:autoPickLineup(code),players=ids.map(id=>PLAYER_BY_ID.get(id)).filter(Boolean),condition=user?avg(players.map(p=>c.playerState[p.id]?.condition||100)):94;let power=avg(players.map(p=>p.rating))+(TEAM_ELO[code]-1800)/34+(home?2.4:0)+(condition-90)/6;if(user){const t=c.tactics;power+=(t.mentality==='Ofensiva'?1.2:t.mentality==='Defensiva'?-1:0)+(t.tempo-55)/45+(t.pressing-55)/55}return{power,players,ids}}
function poisson(random,lambda){let k=0,p=1,L=Math.exp(-lambda);do{k++;p*=random()}while(p>L&&k<9);return k-1}
function weighted(random,players){const rows=players.map(p=>({p,w:p.group==='FWD'?5:p.group==='MID'?2.4:p.group==='DEF'?.55:.08})),sum=rows.reduce((s,r)=>s+r.w,0);let roll=random()*sum;for(const r of rows){roll-=r.w;if(roll<=0)return r.p}return rows.at(-1)?.p}
function distributeEvents(random,goals,side,players){const minutes=new Set,out=[];for(let i=0;i<goals;i++){let m=5+Math.floor(random()*84);while(minutes.has(m))m=5+Math.floor(random()*84);minutes.add(m);const scorer=weighted(random,players),assist=random()>.18?weighted(random,players.filter(p=>p.id!==scorer?.id)):null;out.push({type:'goal',minute:m,side,playerId:scorer?.id||null,playerName:scorer?.name||'Gol',assistPlayerId:assist?.id||null,assistName:assist?.name||null})}return out}
export function simulateFixture(c,f){const random=seededRandom(`${c.seasonId}:${f.id}:${c.clubCode}`),h=teamProfile(c,f.home,true),a=teamProfile(c,f.away,false),diff=(h.power-a.power)/11;const hx=clamp(1.45+diff*.26+(random()-.5)*.35,.25,3.7),ax=clamp(1.16-diff*.23+(random()-.5)*.35,.2,3.5),hg=poisson(random,hx),ag=poisson(random,ax);const events=[...distributeEvents(random,hg,'home',h.players),...distributeEvents(random,ag,'away',a.players)].sort((x,y)=>x.minute-y.minute);const possession=clamp(Math.round(50+diff*3+(random()-.5)*7),31,69);return{fixtureId:f.id,matchweek:f.matchweek,date:f.date,time:f.time,home:f.home,away:f.away,homeGoals:hg,awayGoals:ag,lineups:{home:h.ids,away:a.ids},events,stats:{home:{xg:+hx.toFixed(2),shots:Math.max(hg,Math.round(hx*5.5+random()*4)),possession,corners:2+Math.floor(random()*8)},away:{xg:+ax.toFixed(2),shots:Math.max(ag,Math.round(ax*5.5+random()*4)),possession:100-possession,corners:2+Math.floor(random()*8)}}}}
function userForm(c,r){const home=r.home===c.clubCode,scored=home?r.homeGoals:r.awayGoals,conceded=home?r.awayGoals:r.homeGoals;return scored>conceded?'W':scored<conceded?'L':'D'}
function stats(c,r){for(const id of [...r.lineups.home,...r.lineups.away]){const s=c.playerStats[id]||{appearances:0,goals:0,assists:0};s.appearances++;c.playerStats[id]=s}for(const e of r.events){if(e.playerId){const s=c.playerStats[e.playerId]||{appearances:0,goals:0,assists:0};s.goals++;c.playerStats[e.playerId]=s}if(e.assistPlayerId){const s=c.playerStats[e.assistPlayerId]||{appearances:0,goals:0,assists:0};s.assists++;c.playerStats[e.assistPlayerId]=s}}}
export function commitResult(c,r){if(c.results[r.fixtureId])return c;c.results[r.fixtureId]=r;stats(c,r);if(r.home===c.clubCode||r.away===c.clubCode){const form=userForm(c,r);for(const id of c.lineup){const s=c.playerState[id];if(s){s.condition=clamp(s.condition-(8+hashString(`${r.fixtureId}:${id}`)%8),48,100);s.sharpness=clamp(s.sharpness+2,0,100);s.morale=clamp(s.morale+(form==='W'?4:form==='L'?-4:1),20,100)}}c.recentForm=[form,...c.recentForm].slice(0,5);c.boardConfidence=clamp(c.boardConfidence+(form==='W'?3:form==='L'?-3:1),10,100);const home=r.home===c.clubCode,opp=CLUB_BY_CODE.get(home?r.away:r.home);c.inbox.unshift({id:`match-report-${r.fixtureId}`,date:r.date,sender:'Analista',subject:`${form==='W'?'Vitória':form==='L'?'Derrota':'Empate'} contra ${opp?.name}`,body:`Placar final ${home?r.homeGoals:r.awayGoals}–${home?r.awayGoals:r.homeGoals}. Relatório completo no calendário.`,read:false})}c.updatedAt=new Date().toISOString();return c}
function recover(c){const gain=c.trainingFocus==='Recuperação'?6:c.trainingFocus==='Intensivo'?2:4;for(const s of Object.values(c.playerState)){s.condition=clamp(s.condition+gain,0,100);s.sharpness=clamp(s.sharpness+(c.trainingFocus==='Intensivo'?3:1),0,100)}}
export function advanceOneDay(c){const user=fixturesOnDate(c.currentDate).find(f=>!c.results[f.id]&&(f.home===c.clubCode||f.away===c.clubCode));for(const f of fixturesOnDate(c.currentDate))if(!c.results[f.id]&&f!==user)commitResult(c,simulateFixture(c,f));if(user)return{career:c,ready:true,fixture:user};recover(c);c.currentDate=addDays(c.currentDate);if(c.currentDate>SEASON_END_DATE&&Object.keys(c.results).length===FIXTURES.length){c.status='complete';c.seasonSummary=buildSeasonSummary(c)}return{career:c,ready:false,fixture:null}}
export function continueToNextMatch(c){for(let i=0;i<400;i++){const step=advanceOneDay(c);if(step.ready||c.status==='complete')return step}throw new Error('Calendar guard exceeded')}
export function completePreparedUserMatch(c,r){const f=FIXTURES.find(x=>x.id===r?.fixtureId);if(!f||c.results[f.id])return{career:c,fixture:f,result:c.results[f?.id]};commitResult(c,r);for(const ai of fixturesOnDate(c.currentDate))if(!c.results[ai.id])commitResult(c,simulateFixture(c,ai));recover(c);c.currentDate=addDays(c.currentDate);if(Object.keys(c.results).length===FIXTURES.length){c.status='complete';c.seasonSummary=buildSeasonSummary(c)}return{career:c,fixture:f,result:r}}
export function playCurrentUserFixture(c){const f=fixturesOnDate(c.currentDate).find(x=>!c.results[x.id]&&(x.home===c.clubCode||x.away===c.clubCode));return f?completePreparedUserMatch(c,simulateFixture(c,f)):{career:c,fixture:null,result:null}}
export function setFormation(c,f){if(SHAPES[f]){c.formation=f;c.lineup=autoPickLineup(c.clubCode,f,c.playerState)}return c}
export function setTactic(c,k,v){if(k==='mentality')c.tactics[k]=String(v);else if(['pressing','tempo','width','defensiveLine'].includes(k))c.tactics[k]=clamp(Number(v),20,90);return c}
export function toggleLineupPlayer(c,id){const p=PLAYER_BY_ID.get(id);if(!p||p.clubCode!==c.clubCode)return c;const set=new Set(c.lineup);if(set.has(id)&&set.size>1)set.delete(id);else if(set.size<11)set.add(id);else{const selected=[...set].map(x=>PLAYER_BY_ID.get(x)).filter(Boolean),same=selected.filter(x=>x.group===p.group).sort((a,b)=>a.rating-b.rating);set.delete((same[0]||selected.sort((a,b)=>a.rating-b.rating)[0]).id);set.add(id)}c.lineup=[...set];return c}
export function deriveTable(c){const rows=Object.fromEntries(CLUB_CATALOG.map(x=>[x.code,{code:x.code,name:x.name,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,points:0}]));for(const r of Object.values(c.results)){const h=rows[r.home],a=rows[r.away];h.played++;a.played++;h.gf+=r.homeGoals;h.ga+=r.awayGoals;a.gf+=r.awayGoals;a.ga+=r.homeGoals;if(r.homeGoals>r.awayGoals){h.wins++;a.losses++;h.points+=3}else if(r.homeGoals<r.awayGoals){a.wins++;h.losses++;a.points+=3}else{h.draws++;a.draws++;h.points++;a.points++}}return Object.values(rows).map(x=>({...x,gd:x.gf-x.ga})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.name.localeCompare(b.name)).map((x,i)=>({...x,position:i+1}))}
export function topScorers(c,n=10){return Object.entries(c.playerStats).map(([id,s])=>({player:PLAYER_BY_ID.get(id),...s})).filter(x=>x.player&&x.goals).sort((a,b)=>b.goals-a.goals||b.assists-a.assists).slice(0,n)}
export function buildSeasonSummary(c){const r=deriveTable(c).find(x=>x.code===c.clubCode);return{position:r?.position||20,points:r?.points||0,wins:r?.wins||0,draws:r?.draws||0,losses:r?.losses||0,boardConfidence:c.boardConfidence,completedAt:new Date().toISOString()}}
export function completeSeasonForTest(c){for(let i=0;i<500&&Object.keys(c.results).length<FIXTURES.length;i++){const user=fixturesOnDate(c.currentDate).some(f=>!c.results[f.id]&&(f.home===c.clubCode||f.away===c.clubCode));user?playCurrentUserFixture(c):advanceOneDay(c)}return c}
